apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: write-helmvalues
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=docker.io/bitnami/nginx:1.27.x
    argocd-image-updater.argoproj.io/update-strategy: semver
    argocd-image-updater.argoproj.io/force-update: "false"
    argocd-image-updater.argoproj.io/nginx.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/git-repository: https://github.com/chengfang/image-updater-examples.git
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/write-back-target: helmvalues
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: "18.2.3"
      chart: nginx
      helm:
        valueFiles:
          - $values/write-helmvalues/source2/values.yaml
    - repoURL: https://github.com/chengfang/image-updater-examples.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
